// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfqaytekoovmcmcvwisn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmcWF5dGVrb292bWNtY3Z3aXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjg2MTUsImV4cCI6MjA2NDgwNDYxNX0.nDg4gYMB98LzQVtZITYBdcJvBkSgGqCqV8PmClAjJp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);